import {
  Department,
  Course,
  Subject,
  Student,
  Faculty,
  User,
  AttendanceRecord,
  MarkRecord,
  Notice,
  TimetableSlot,
  SystemSettings
} from '../types';

export const INITIAL_SETTINGS: SystemSettings = {
  academicYear: '2026-2027',
  currentSemesterType: 'Odd',
  minAttendancePercentage: 75,
  universityName: 'C.V. Raman Global University',
  departmentName: 'Department of Computer Science & Engineering',
  gradingScheme: 'Standard 10-Point',
};

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-cse',
    code: 'CSE',
    name: 'Computer Science & Engineering',
    hodName: 'Dr. Rajesh Mohanty',
    hodEmail: 'hod.cse@cgu-odisha.ac.in',
    establishedYear: 2001,
    description: 'Premier department dedicated to cutting-edge research in algorithms, distributed systems, software engineering, and artificial intelligence.',
    facultyCount: 24,
    studentCount: 480,
    coursesOffered: ['B.Tech CSE', 'M.Tech CSE', 'Ph.D Computer Science'],
  },
  {
    id: 'dept-ece',
    code: 'ECE',
    name: 'Electronics & Communication Engineering',
    hodName: 'Dr. Sunita Pattnaik',
    hodEmail: 'hod.ece@cgu-odisha.ac.in',
    establishedYear: 2002,
    description: 'Center of excellence in embedded systems, signal processing, VLSI design, and telecommunication technologies.',
    facultyCount: 18,
    studentCount: 360,
    coursesOffered: ['B.Tech ECE', 'M.Tech VLSI'],
  },
  {
    id: 'dept-me',
    code: 'ME',
    name: 'Mechanical Engineering',
    hodName: 'Dr. Debabrata Jena',
    hodEmail: 'hod.me@cgu-odisha.ac.in',
    establishedYear: 1999,
    description: 'Focused on thermodynamics, robotics, additive manufacturing, and computer-integrated production.',
    facultyCount: 16,
    studentCount: 300,
    coursesOffered: ['B.Tech ME'],
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-btech-cse',
    code: 'BTECH-CSE',
    name: 'Bachelor of Technology in Computer Science & Engineering',
    departmentId: 'dept-cse',
    durationYears: 4,
    totalSemesters: 8,
    degreeType: 'Undergraduate',
    curriculumVersion: 'Rev-2024-CBCS',
    status: 'active',
  },
  {
    id: 'course-btech-ece',
    code: 'BTECH-ECE',
    name: 'Bachelor of Technology in Electronics & Communication',
    departmentId: 'dept-ece',
    durationYears: 4,
    totalSemesters: 8,
    degreeType: 'Undergraduate',
    curriculumVersion: 'Rev-2024-CBCS',
    status: 'active',
  },
  {
    id: 'course-mtech-cse',
    code: 'MTECH-CSE',
    name: 'Master of Technology in Computer Science',
    departmentId: 'dept-cse',
    durationYears: 2,
    totalSemesters: 4,
    degreeType: 'Postgraduate',
    curriculumVersion: 'Rev-2025',
    status: 'active',
  },
];

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'subj-cs301',
    code: 'CS301',
    name: 'Data Structures & Algorithms',
    departmentId: 'dept-cse',
    courseId: 'course-btech-cse',
    semester: 5,
    credits: 4,
    type: 'Theory',
    assignedFacultyId: 'fac-001',
    assignedFacultyName: 'Dr. Rajesh Mohanty',
    totalClassesScheduled: 42,
    description: 'Advanced trees, graphs, dynamic programming, hashing, and complexity analysis.',
  },
  {
    id: 'subj-cs302',
    code: 'CS302',
    name: 'Database Management Systems',
    departmentId: 'dept-cse',
    courseId: 'course-btech-cse',
    semester: 5,
    credits: 4,
    type: 'Theory',
    assignedFacultyId: 'fac-002',
    assignedFacultyName: 'Prof. Ananya Sengupta',
    totalClassesScheduled: 40,
    description: 'Relational algebra, SQL, normalization (1NF-BCNF), concurrency control, and transactions.',
  },
  {
    id: 'subj-cs303',
    code: 'CS303',
    name: 'Software Engineering & Agile Methodologies',
    departmentId: 'dept-cse',
    courseId: 'course-btech-cse',
    semester: 5,
    credits: 3,
    type: 'Theory',
    assignedFacultyId: 'fac-003',
    assignedFacultyName: 'Dr. Vikramaditya Rath',
    totalClassesScheduled: 36,
    description: 'SDLC, Agile Scrum, requirements modeling, software design patterns, and QA testing.',
  },
  {
    id: 'subj-cs304',
    code: 'CS304',
    name: 'Operating Systems & System Programming',
    departmentId: 'dept-cse',
    courseId: 'course-btech-cse',
    semester: 5,
    credits: 4,
    type: 'Theory',
    assignedFacultyId: 'fac-004',
    assignedFacultyName: 'Prof. Meera Nair',
    totalClassesScheduled: 38,
    description: 'Process management, threads, CPU scheduling, synchronization, deadlock, and virtual memory.',
  },
  {
    id: 'subj-cs305',
    code: 'CS305',
    name: 'Computer Networks & Protocols',
    departmentId: 'dept-cse',
    courseId: 'course-btech-cse',
    semester: 5,
    credits: 3,
    type: 'Theory',
    assignedFacultyId: 'fac-005',
    assignedFacultyName: 'Dr. Arindam Bose',
    totalClassesScheduled: 35,
    description: 'OSI & TCP/IP stack, routing protocols, flow control, transport layer security, and socket programming.',
  },
  {
    id: 'subj-cs306l',
    code: 'CS306L',
    name: 'DBMS & Systems Laboratory',
    departmentId: 'dept-cse',
    courseId: 'course-btech-cse',
    semester: 5,
    credits: 2,
    type: 'Practical',
    assignedFacultyId: 'fac-002',
    assignedFacultyName: 'Prof. Ananya Sengupta',
    totalClassesScheduled: 20,
    description: 'Hands-on query execution, indexing, stored procedures, triggers, and POSIX system calls.',
  },
  {
    id: 'subj-ec301',
    code: 'EC301',
    name: 'Digital Signal Processing',
    departmentId: 'dept-ece',
    courseId: 'course-btech-ece',
    semester: 5,
    credits: 4,
    type: 'Theory',
    assignedFacultyId: 'fac-006',
    assignedFacultyName: 'Dr. Sunita Pattnaik',
    totalClassesScheduled: 38,
    description: 'DFT, FFT, IIR/FIR filter design, multi-rate DSP, and spectral estimation.',
  },
];

export const INITIAL_FACULTY: Faculty[] = [
  {
    id: 'fac-001',
    facultyId: 'FAC-CSE-01',
    name: 'Dr. Rajesh Mohanty',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    designation: 'Professor & HOD',
    email: 'hod.cse@cgu-odisha.ac.in',
    phone: '+91 94371 82910',
    qualification: 'Ph.D. in Computer Science (IIT Kharagpur)',
    specialization: 'Distributed Systems & Advanced Algorithms',
    joiningDate: '2012-07-15',
    assignedSubjectIds: ['subj-cs301'],
    status: 'active',
    officeRoom: 'Tech Block 3, Room 401',
  },
  {
    id: 'fac-002',
    facultyId: 'FAC-CSE-02',
    name: 'Prof. Ananya Sengupta',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    designation: 'Associate Professor',
    email: 'ananya.s@cgu-odisha.ac.in',
    phone: '+91 98610 44219',
    qualification: 'M.Tech (NIT Rourkela), Ph.D. Candidate',
    specialization: 'Database Systems & Data Mining',
    joiningDate: '2016-08-01',
    assignedSubjectIds: ['subj-cs302', 'subj-cs306l'],
    status: 'active',
    officeRoom: 'Tech Block 3, Room 308',
  },
  {
    id: 'fac-003',
    facultyId: 'FAC-CSE-03',
    name: 'Dr. Vikramaditya Rath',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    designation: 'Associate Professor',
    email: 'vikram.rath@cgu-odisha.ac.in',
    phone: '+91 94380 55122',
    qualification: 'Ph.D. in Software Engineering (IIIT Hyderabad)',
    specialization: 'Software Architecture & Cloud Native Apps',
    joiningDate: '2018-01-10',
    assignedSubjectIds: ['subj-cs303'],
    status: 'active',
    officeRoom: 'Tech Block 3, Room 312',
  },
  {
    id: 'fac-004',
    facultyId: 'FAC-CSE-04',
    name: 'Prof. Meera Nair',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    designation: 'Assistant Professor',
    email: 'meera.nair@cgu-odisha.ac.in',
    phone: '+91 97762 90114',
    qualification: 'M.Tech in CS (BITS Pilani)',
    specialization: 'Operating Systems & Kernel Programming',
    joiningDate: '2020-09-01',
    assignedSubjectIds: ['subj-cs304'],
    status: 'active',
    officeRoom: 'Tech Block 3, Room 204',
  },
  {
    id: 'fac-005',
    facultyId: 'FAC-CSE-05',
    name: 'Dr. Arindam Bose',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    designation: 'Professor',
    email: 'arindam.bose@cgu-odisha.ac.in',
    phone: '+91 94392 31800',
    qualification: 'Ph.D. in Network Security (IISc Bangalore)',
    specialization: 'Computer Networks, Cryptography & Cybersecurity',
    joiningDate: '2014-06-20',
    assignedSubjectIds: ['subj-cs305'],
    status: 'active',
    officeRoom: 'Tech Block 3, Room 410',
  },
  {
    id: 'fac-006',
    facultyId: 'FAC-ECE-01',
    name: 'Dr. Sunita Pattnaik',
    departmentId: 'dept-ece',
    departmentName: 'Electronics & Communication Engineering',
    designation: 'Professor & HOD',
    email: 'hod.ece@cgu-odisha.ac.in',
    phone: '+91 94370 77123',
    qualification: 'Ph.D. in Signal Processing (IIT Roorkee)',
    specialization: 'Digital Signal Processing & Image Restoration',
    joiningDate: '2013-05-11',
    assignedSubjectIds: ['subj-ec301'],
    status: 'active',
    officeRoom: 'ECE Block 1, Room 201',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu-001',
    studentId: 'STU2024001',
    name: 'Ayush Kumar Das',
    rollNumber: '2401020374',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    currentSemester: 5,
    email: '2401020374@cgu-odisha.ac.in',
    phone: '+91 91234 56789',
    dateOfBirth: '2004-05-18',
    bloodGroup: 'O+',
    address: 'Plot 42, Khandagiri Enclave, Bhubaneswar, Odisha',
    guardianName: 'Manoj Kumar Das',
    guardianPhone: '+91 98610 11223',
    enrollmentYear: 2024,
    status: 'active',
    cgpa: 8.92,
    attendancePercentage: 88.5,
  },
  {
    id: 'stu-002',
    studentId: 'STU2024002',
    name: 'Priyanka Priyadarshini',
    rollNumber: '2401020375',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    currentSemester: 5,
    email: 'priyanka.p@cgu-odisha.ac.in',
    phone: '+91 94372 99881',
    dateOfBirth: '2004-08-22',
    bloodGroup: 'A+',
    address: 'Flat 302, Royal Palms, Cuttack Road, Bhubaneswar',
    guardianName: 'Subhashish Mohanty',
    guardianPhone: '+91 94380 44556',
    enrollmentYear: 2024,
    status: 'active',
    cgpa: 9.35,
    attendancePercentage: 94.0,
  },
  {
    id: 'stu-003',
    studentId: 'STU2024003',
    name: 'Rohan Sharma',
    rollNumber: '2401020376',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    currentSemester: 5,
    email: 'rohan.sharma@cgu-odisha.ac.in',
    phone: '+91 98112 33445',
    dateOfBirth: '2004-03-12',
    bloodGroup: 'B+',
    address: 'B-14, Green Valley Colony, Rourkela, Odisha',
    guardianName: 'Satish Sharma',
    guardianPhone: '+91 98110 55667',
    enrollmentYear: 2024,
    status: 'active',
    cgpa: 7.45,
    attendancePercentage: 72.0, // Alert: <75%
  },
  {
    id: 'stu-004',
    studentId: 'STU2024004',
    name: 'Debasmita Sahoo',
    rollNumber: '2401020377',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    currentSemester: 5,
    email: 'debasmita.s@cgu-odisha.ac.in',
    phone: '+91 99370 12894',
    dateOfBirth: '2004-11-05',
    bloodGroup: 'AB+',
    address: 'HIG-24, Sailashree Vihar, Bhubaneswar, Odisha',
    guardianName: 'Niranjan Sahoo',
    guardianPhone: '+91 94371 66778',
    enrollmentYear: 2024,
    status: 'active',
    cgpa: 8.60,
    attendancePercentage: 86.2,
  },
  {
    id: 'stu-005',
    studentId: 'STU2024005',
    name: 'Abhishek Tripathy',
    rollNumber: '2401020378',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    currentSemester: 5,
    email: 'abhishek.t@cgu-odisha.ac.in',
    phone: '+91 96580 87654',
    dateOfBirth: '2004-01-30',
    bloodGroup: 'O-',
    address: 'Qrs 4R-12, HAL Township, Sunabeda, Koraput',
    guardianName: 'Bishnu Charan Tripathy',
    guardianPhone: '+91 96580 11990',
    enrollmentYear: 2024,
    status: 'active',
    cgpa: 8.15,
    attendancePercentage: 81.0,
  },
  {
    id: 'stu-006',
    studentId: 'STU2024006',
    name: 'Sneha Patnaik',
    rollNumber: '2401020379',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    currentSemester: 5,
    email: 'sneha.patnaik@cgu-odisha.ac.in',
    phone: '+91 94375 66778',
    dateOfBirth: '2004-09-14',
    bloodGroup: 'A-',
    address: 'Lane 6, Mallikashpur, Balasore, Odisha',
    guardianName: 'Gopinath Patnaik',
    guardianPhone: '+91 94370 22334',
    enrollmentYear: 2024,
    status: 'active',
    cgpa: 9.10,
    attendancePercentage: 92.5,
  },
  {
    id: 'stu-007',
    studentId: 'STU2024007',
    name: 'Manish Kumar Rout',
    rollNumber: '2401020380',
    departmentId: 'dept-ece',
    departmentName: 'Electronics & Communication Engineering',
    courseId: 'course-btech-ece',
    courseName: 'B.Tech ECE',
    currentSemester: 5,
    email: 'manish.rout@cgu-odisha.ac.in',
    phone: '+91 98612 00991',
    dateOfBirth: '2003-12-08',
    bloodGroup: 'B-',
    address: 'Station Road, Berhampur, Ganjam, Odisha',
    guardianName: 'Santosh Rout',
    guardianPhone: '+91 98610 88776',
    enrollmentYear: 2024,
    status: 'active',
    cgpa: 7.90,
    attendancePercentage: 78.4,
  },
  {
    id: 'stu-008',
    studentId: 'STU2024008',
    name: 'Anwesha Mishra',
    rollNumber: '2401020381',
    departmentId: 'dept-ece',
    departmentName: 'Electronics & Communication Engineering',
    courseId: 'course-btech-ece',
    courseName: 'B.Tech ECE',
    currentSemester: 5,
    email: 'anwesha.m@cgu-odisha.ac.in',
    phone: '+91 94391 44556',
    dateOfBirth: '2004-06-25',
    bloodGroup: 'O+',
    address: 'Madhupatna, Cuttack, Odisha',
    guardianName: 'Pradeep Mishra',
    guardianPhone: '+91 94390 11223',
    enrollmentYear: 2024,
    status: 'active',
    cgpa: 8.80,
    attendancePercentage: 89.0,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    username: 'admin',
    name: 'Dr. Rajesh Mohanty',
    email: 'hod.cse@cgu-odisha.ac.in',
    role: 'admin',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    phone: '+91 94371 82910',
    status: 'active',
    lastLogin: '2026-10-02 18:45',
  },
  {
    id: 'user-fac-002',
    username: 'ananya.s',
    name: 'Prof. Ananya Sengupta',
    email: 'ananya.s@cgu-odisha.ac.in',
    role: 'faculty',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    phone: '+91 98610 44219',
    status: 'active',
    lastLogin: '2026-10-02 19:10',
  },
  {
    id: 'user-stu-001',
    username: '2401020374',
    name: 'Ayush Kumar Das',
    email: '2401020374@cgu-odisha.ac.in',
    role: 'student',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    phone: '+91 91234 56789',
    status: 'active',
    lastLogin: '2026-10-02 20:30',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-2026-10-02-cs302',
    date: '2026-10-02',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    subjectId: 'subj-cs302',
    subjectName: 'Database Management Systems',
    subjectCode: 'CS302',
    facultyId: 'fac-002',
    facultyName: 'Prof. Ananya Sengupta',
    semester: 5,
    entries: [
      { studentId: 'stu-001', studentName: 'Ayush Kumar Das', rollNumber: '2401020374', status: 'present' },
      { studentId: 'stu-002', studentName: 'Priyanka Priyadarshini', rollNumber: '2401020375', status: 'present' },
      { studentId: 'stu-003', studentName: 'Rohan Sharma', rollNumber: '2401020376', status: 'absent' },
      { studentId: 'stu-004', studentName: 'Debasmita Sahoo', rollNumber: '2401020377', status: 'present' },
      { studentId: 'stu-005', studentName: 'Abhishek Tripathy', rollNumber: '2401020378', status: 'present' },
      { studentId: 'stu-006', studentName: 'Sneha Patnaik', rollNumber: '2401020379', status: 'present' },
    ],
    totalStudents: 6,
    presentCount: 5,
    absentCount: 1,
    attendancePercentage: 83.3,
    timestamp: '2026-10-02 11:05',
  },
  {
    id: 'att-2026-10-01-cs301',
    date: '2026-10-01',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    subjectId: 'subj-cs301',
    subjectName: 'Data Structures & Algorithms',
    subjectCode: 'CS301',
    facultyId: 'fac-001',
    facultyName: 'Dr. Rajesh Mohanty',
    semester: 5,
    entries: [
      { studentId: 'stu-001', studentName: 'Ayush Kumar Das', rollNumber: '2401020374', status: 'present' },
      { studentId: 'stu-002', studentName: 'Priyanka Priyadarshini', rollNumber: '2401020375', status: 'present' },
      { studentId: 'stu-003', studentName: 'Rohan Sharma', rollNumber: '2401020376', status: 'present' },
      { studentId: 'stu-004', studentName: 'Debasmita Sahoo', rollNumber: '2401020377', status: 'present' },
      { studentId: 'stu-005', studentName: 'Abhishek Tripathy', rollNumber: '2401020378', status: 'present' },
      { studentId: 'stu-006', studentName: 'Sneha Patnaik', rollNumber: '2401020379', status: 'present' },
    ],
    totalStudents: 6,
    presentCount: 6,
    absentCount: 0,
    attendancePercentage: 100.0,
    timestamp: '2026-10-01 10:15',
  },
  {
    id: 'att-2026-09-30-cs303',
    date: '2026-09-30',
    courseId: 'course-btech-cse',
    courseName: 'B.Tech CSE',
    subjectId: 'subj-cs303',
    subjectName: 'Software Engineering & Agile Methodologies',
    subjectCode: 'CS303',
    facultyId: 'fac-003',
    facultyName: 'Dr. Vikramaditya Rath',
    semester: 5,
    entries: [
      { studentId: 'stu-001', studentName: 'Ayush Kumar Das', rollNumber: '2401020374', status: 'present' },
      { studentId: 'stu-002', studentName: 'Priyanka Priyadarshini', rollNumber: '2401020375', status: 'present' },
      { studentId: 'stu-003', studentName: 'Rohan Sharma', rollNumber: '2401020376', status: 'absent' },
      { studentId: 'stu-004', studentName: 'Debasmita Sahoo', rollNumber: '2401020377', status: 'present' },
      { studentId: 'stu-005', studentName: 'Abhishek Tripathy', rollNumber: '2401020378', status: 'absent' },
      { studentId: 'stu-006', studentName: 'Sneha Patnaik', rollNumber: '2401020379', status: 'present' },
    ],
    totalStudents: 6,
    presentCount: 4,
    absentCount: 2,
    attendancePercentage: 66.7,
    timestamp: '2026-09-30 14:10',
  },
];

export const INITIAL_MARKS: MarkRecord[] = [
  // CS301 Marks
  {
    id: 'mrk-001',
    studentId: 'stu-001',
    studentName: 'Ayush Kumar Das',
    rollNumber: '2401020374',
    subjectId: 'subj-cs301',
    subjectName: 'Data Structures & Algorithms',
    subjectCode: 'CS301',
    courseId: 'course-btech-cse',
    semester: 5,
    examType: 'Internal',
    maxMarks: 50,
    marksObtained: 44,
    percentage: 88,
    grade: 'A+',
    evaluatedBy: 'Dr. Rajesh Mohanty',
    evaluationDate: '2026-09-25',
    remarks: 'Strong understanding of binary search trees and amortized complexity.',
  },
  {
    id: 'mrk-002',
    studentId: 'stu-001',
    studentName: 'Ayush Kumar Das',
    rollNumber: '2401020374',
    subjectId: 'subj-cs302',
    subjectName: 'Database Management Systems',
    subjectCode: 'CS302',
    courseId: 'course-btech-cse',
    semester: 5,
    examType: 'Internal',
    maxMarks: 50,
    marksObtained: 46,
    percentage: 92,
    grade: 'O',
    evaluatedBy: 'Prof. Ananya Sengupta',
    evaluationDate: '2026-09-26',
    remarks: 'Flawless schema normalization and SQL query design.',
  },
  {
    id: 'mrk-003',
    studentId: 'stu-001',
    studentName: 'Ayush Kumar Das',
    rollNumber: '2401020374',
    subjectId: 'subj-cs303',
    subjectName: 'Software Engineering & Agile Methodologies',
    subjectCode: 'CS303',
    courseId: 'course-btech-cse',
    semester: 5,
    examType: 'Sessional',
    maxMarks: 100,
    marksObtained: 85,
    percentage: 85,
    grade: 'A+',
    evaluatedBy: 'Dr. Vikramaditya Rath',
    evaluationDate: '2026-09-28',
    remarks: 'Comprehensive project architecture document submitted.',
  },
  {
    id: 'mrk-004',
    studentId: 'stu-001',
    studentName: 'Ayush Kumar Das',
    rollNumber: '2401020374',
    subjectId: 'subj-cs304',
    subjectName: 'Operating Systems & System Programming',
    subjectCode: 'CS304',
    courseId: 'course-btech-cse',
    semester: 5,
    examType: 'Internal',
    maxMarks: 50,
    marksObtained: 41,
    percentage: 82,
    grade: 'A',
    evaluatedBy: 'Prof. Meera Nair',
    evaluationDate: '2026-09-24',
    remarks: 'Good handling of Peterson algorithm and semaphore synchronization.',
  },
  {
    id: 'mrk-005',
    studentId: 'stu-002',
    studentName: 'Priyanka Priyadarshini',
    rollNumber: '2401020375',
    subjectId: 'subj-cs301',
    subjectName: 'Data Structures & Algorithms',
    subjectCode: 'CS301',
    courseId: 'course-btech-cse',
    semester: 5,
    examType: 'Internal',
    maxMarks: 50,
    marksObtained: 48,
    percentage: 96,
    grade: 'O',
    evaluatedBy: 'Dr. Rajesh Mohanty',
    evaluationDate: '2026-09-25',
    remarks: 'Exceptional graph algorithmic optimization.',
  },
  {
    id: 'mrk-006',
    studentId: 'stu-003',
    studentName: 'Rohan Sharma',
    rollNumber: '2401020376',
    subjectId: 'subj-cs301',
    subjectName: 'Data Structures & Algorithms',
    subjectCode: 'CS301',
    courseId: 'course-btech-cse',
    semester: 5,
    examType: 'Internal',
    maxMarks: 50,
    marksObtained: 32,
    percentage: 64,
    grade: 'B',
    evaluatedBy: 'Dr. Rajesh Mohanty',
    evaluationDate: '2026-09-25',
    remarks: 'Needs practice with recursion and dynamic programming.',
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-001',
    title: 'Mid-Semester Examination Schedule — Autumn 2026',
    content: 'The Mid-Semester Theory Examinations for 5th & 7th Semester B.Tech will commence from October 19, 2026. Detailed seating matrix and hall ticket issuance instructions will be published on the UDIS portal next Monday. All students must ensure minimum 75% attendance to obtain hall tickets.',
    postedBy: 'Dr. Rajesh Mohanty',
    postedByRole: 'Head of Department (CSE)',
    postedDate: '2026-10-02',
    targetAudience: 'All',
    priority: 'urgent',
    status: 'published',
  },
  {
    id: 'not-002',
    title: 'Submission of 5th Semester Mini-Project Synopsis',
    content: 'All 5th Semester B.Tech CSE students are hereby instructed to submit their Project Synopsis for CS303 (Software Engineering) approved by their respective faculty guides on or before October 12, 2026. Late submissions will result in a deduction of internal evaluation marks.',
    postedBy: 'Dr. Vikramaditya Rath',
    postedByRole: 'Project Coordinator',
    postedDate: '2026-10-01',
    targetAudience: 'Students',
    priority: 'high',
    status: 'published',
  },
  {
    id: 'not-003',
    title: 'Faculty Academic Council Meeting on Curriculum Revision',
    content: 'All Department Faculty members are requested to attend the departmental Academic Council meeting on October 07, 2026, at 3:30 PM in Conference Room A. Agenda includes reviewing NBA accreditation files and elective subject allocations for the upcoming spring term.',
    postedBy: 'Dr. Rajesh Mohanty',
    postedByRole: 'HOD CSE',
    postedDate: '2026-09-29',
    targetAudience: 'Faculty',
    priority: 'normal',
    status: 'published',
  },
  {
    id: 'not-004',
    title: 'Campus Recruitment Drive — Cloud Solutions & FinTech',
    content: 'Pre-placement talks by Tier-1 software organizations for final year and pre-final year students will take place on Saturday, October 10 in the Central Auditorium. Eligible students must carry three updated physical resumes and college ID.',
    postedBy: 'Training & Placement Cell',
    postedByRole: 'Placement Officer',
    postedDate: '2026-09-27',
    targetAudience: 'Students',
    priority: 'high',
    status: 'published',
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // Monday
  { id: 'tt-1', day: 'Monday', time: '09:00 AM - 10:00 AM', subjectCode: 'CS301', subjectName: 'Data Structures & Algorithms', facultyName: 'Dr. Rajesh Mohanty', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-2', day: 'Monday', time: '10:00 AM - 11:00 AM', subjectCode: 'CS302', subjectName: 'Database Management Systems', facultyName: 'Prof. Ananya Sengupta', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-3', day: 'Monday', time: '11:15 AM - 12:15 PM', subjectCode: 'CS304', subjectName: 'Operating Systems', facultyName: 'Prof. Meera Nair', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-4', day: 'Monday', time: '01:30 PM - 03:30 PM', subjectCode: 'CS306L', subjectName: 'DBMS Laboratory', facultyName: 'Prof. Ananya Sengupta', roomNumber: 'CS Lab 2', courseId: 'course-btech-cse', semester: 5 },

  // Tuesday
  { id: 'tt-5', day: 'Tuesday', time: '09:00 AM - 10:00 AM', subjectCode: 'CS303', subjectName: 'Software Engineering', facultyName: 'Dr. Vikramaditya Rath', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-6', day: 'Tuesday', time: '10:00 AM - 11:00 AM', subjectCode: 'CS305', subjectName: 'Computer Networks', facultyName: 'Dr. Arindam Bose', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-7', day: 'Tuesday', time: '11:15 AM - 12:15 PM', subjectCode: 'CS301', subjectName: 'Data Structures & Algorithms', facultyName: 'Dr. Rajesh Mohanty', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },

  // Wednesday
  { id: 'tt-8', day: 'Wednesday', time: '09:00 AM - 10:00 AM', subjectCode: 'CS302', subjectName: 'Database Management Systems', facultyName: 'Prof. Ananya Sengupta', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-9', day: 'Wednesday', time: '10:00 AM - 11:00 AM', subjectCode: 'CS304', subjectName: 'Operating Systems', facultyName: 'Prof. Meera Nair', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-10', day: 'Wednesday', time: '11:15 AM - 12:15 PM', subjectCode: 'CS303', subjectName: 'Software Engineering', facultyName: 'Dr. Vikramaditya Rath', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },

  // Thursday
  { id: 'tt-11', day: 'Thursday', time: '09:00 AM - 10:00 AM', subjectCode: 'CS305', subjectName: 'Computer Networks', facultyName: 'Dr. Arindam Bose', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-12', day: 'Thursday', time: '10:00 AM - 11:00 AM', subjectCode: 'CS301', subjectName: 'Data Structures & Algorithms', facultyName: 'Dr. Rajesh Mohanty', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-13', day: 'Thursday', time: '02:00 PM - 04:00 PM', subjectCode: 'CS303', subjectName: 'Project Mentoring & Agile Lab', facultyName: 'Dr. Vikramaditya Rath', roomNumber: 'Project Lab 4', courseId: 'course-btech-cse', semester: 5 },

  // Friday
  { id: 'tt-14', day: 'Friday', time: '09:00 AM - 10:00 AM', subjectCode: 'CS304', subjectName: 'Operating Systems', facultyName: 'Prof. Meera Nair', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-15', day: 'Friday', time: '10:00 AM - 11:00 AM', subjectCode: 'CS302', subjectName: 'Database Management Systems', facultyName: 'Prof. Ananya Sengupta', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
  { id: 'tt-16', day: 'Friday', time: '11:15 AM - 12:15 PM', subjectCode: 'CS305', subjectName: 'Computer Networks', facultyName: 'Dr. Arindam Bose', roomNumber: 'LH-301', courseId: 'course-btech-cse', semester: 5 },
];
